design_name: "NewAxe_Cargo"
description: "Test Study Parameters for direct2cad Run"
# The 'flight_paths' entry must be a list.  The 'analysis_type' is a
# single integer number.  All other FDM parameters can 
# be a single value or a list. If a list exists, it should be the same 
# size as the 'flight_path' list
num_samples: 500
fdm:
  Analysis_Type: 3
  Flight_Path: [1, 3, 4, 5]
  Requested_Lateral_Speed: [19, 21, 11, 10]
  Requested_Vertical_Speed: 1.1
  Q_Position: 1
  Q_Velocity: 1
  Q_Angular_Velocity: 1
  Q_Angles: 1
  Ctrl_R: 0.1
params:
  # rear_rail_r, rear_rail_l
  rear_rail_insts: 
    max_value: 440
    min_value: 75
    name: 
      - Rear_Rail
    parameter: Length
  # capsule_fuselage, vertical_l, bottom_leg_l, vertical_r, bottom_leg_r
  tube_vert:
    max_value: 500
    min_value: 75
    name: 
      - Vertical_Tube
    parameter: Length
  # front_rail_r, front_rail_l
  front_rail_insts:
    max_value: 440
    min_value: 75
    name: 
      - Front_Rail
    parameter: Length
  # front_wing_tube_l, front_wing_tube_r
  front_wing_tubes:
    max_value: 100
    min_value: 25
    name: 
      - Front_Wing_Tube
    parameter: Length
  # top_leg_r, top_leg_l
  top_leg_tubes:
    max_value: 450
    min_value: 50
    name: 
      - Top_Leg_Tube
    parameter: Length
  # right_rudder, left_rudder
  #rudder_chord:
  #  max_value: 300
  #  min_value: 50
  #  name: 
  #    - rudder
  #  parameter: chord
  # rudder_tube_r,rudder_tube_l
  rudder_tube:
    max_value: 120
    min_value: 20
    name: 
      - Rudder_Tube
    parameter: Length
  # front_right_wing, front_left_wing
  #front_wing_chord:
  #  max_value: 300
  #  min_value: 50
  #  name: 
  #    - front_wing
  #  parameter: chord
  # rear_right_wing, rear_left_wing
  #rear_wing_chord:
  #  max_value: 300
  #  min_value: 50
  #  name: rear_wing
  #    - 
  #  parameter: chord