design_name: "PickAxeVU"
description: "Test Study Parameters for direct2cad Run"
# The 'flight_paths' entry must be a list.  The 'analysis_type' is a
# single integer number.  All other FDM parameters can 
# be a single value or a list. If a list exists, it should be the same 
# size as the 'flight_path' list
num_samples: 10
fdm:
  Analysis_Type: 3
  Flight_Path: [9]
  Requested_Lateral_Speed: 19
  Requested_Vertical_Speed: -2
  Requested_Vertical_Down_Speed: 2
  Requested_Lateral_Acceleration: 0.125
  Requested_Lateral_Deceleration: -0.125
  Requested_Vertical_Acceleration: -0.2
  Requested_Vertical_Deceleration: 0.2
  Landing_Approach_Height: 3
  Vertical_Landing_Speed_At_Ground: 0.1
  Q_Position: 1
  Q_Velocity: 1
  Q_Angular_Velocity: 1
  Q_Angles: 1
  Ctrl_R: 0.1
params:
  mid_tube_length:
    min: 75
    max: 440
    components:
      - mid_tube_l
      - mid_tube_r
    parameter: Length
  front_rail_length:
    min: 75
    max: 440
    components: 
      - front_rail_l
      - front_rail_r
    parameter: Length
  front_railDwn_length:
    min: 75
    max: 440
    components: 
      - front_railDwn_l
      - front_railDwn_r
    parameter: Length
  front_railLower_length:
    min: 75
    max: 440
    components: 
      - front_railLower_l
      - front_railLower_r
    parameter: Length
  front_wing_tube_length:
    min: 25
    max: 100
    components: 
      - front_wing_tube_l
      - front_wing_tube_r
    parameter: Length
  rear_rail_length: 
    min: 75
    max: 440
    components: 
      - rear_rail_l
      - rear_rail_r
    parameter: Length
  bottom_leg_length: 
    min: 75
    max: 440
    components: 
      - bottom_leg_l
      - bottom_leg_r
    parameter: Length
  vertical_length: 
    min: 75
    max: 440
    components: 
      - vertical_l
      - vertical_r
    parameter: Length
  top_leg_length: 
    min: 75
    max: 440
    components: 
      - top_leg_l
      - top_leg_r
    parameter: Length
  rudder_tube_length: 
    min: 75
    max: 440
    components: 
      - rudder_tube_l
      - rudder_tube_r
    parameter: Length
  front_wing_span:
    min: 100
    max: 800
    components: 
      - front_left_wing
      - front_right_wing
    parameter: SPAN
  front_wing_chord:
    min: 100
    max: 300
    components: 
      - front_left_wing
      - front_right_wing
    parameter: [CHORD_1, CHORD_2]
  front_wing_thickness:
    min: 6
    max: 25
    components: 
      - front_left_wing
      - front_right_wing
    parameter: THICKNESS
  front_wing_load:
    min: 15
    max: 50
    components: 
      - front_left_wing
      - front_right_wing
    parameter: LOAD
  rear_wing_span:
    min: 100
    max: 800
    components: 
      - rear_left_wing
      - rear_right_wing
    parameter: SPAN
  rear_wing_chord:
    min: 100
    max: 300
    components: 
      - rear_left_wing
      - rear_right_wing
    parameter: [CHORD_1, CHORD_2]
  rear_wing_thickness:
    min: 6
    max: 25
    components: 
      - rear_left_wing
      - rear_right_wing
    parameter: THICKNESS
  rear_wing_load:
    min: 15
    max: 50
    components: 
      - rear_left_wing
      - rear_right_wing
    parameter: LOAD
  rudder_span:
    min: 100
    max: 300
    components: 
      - left_rudder
      - right_rudder
    parameter: SPAN
  rudder_chord:
    min: 100
    max: 200
    components: 
      - left_rudder
      - right_rudder
    parameter: [CHORD_1, CHORD_2]
  rudder_thickness:
    min: 6
    max: 25
    components: 
      - left_rudder
      - right_rudder
    parameter: THICKNESS
  rudder_load:
    min: 15
    max: 50
    components: 
      - left_rudder
      - right_rudder
    parameter: LOAD