design_name: "SuperQuadVU"
description: "Test Study Parameters for direct2cad Run"
# The 'flight_path' entry must be a list.  The 'analysis_type' is a
# single integer number.  All other FDM parameters can 
# be a single value or a list. If a list exists, it should be the same 
# size as the 'flight_path' list
num_samples: 100
fdm:
  Analysis_Type: 3
  Flight_Path: [9]
  Requested_Lateral_Speed: 19
  Requested_Vertical_Speed: -2
  Requested_Vertical_Down_Speed: 2
  Requested_Lateral_Acceleration: 0.125
  Requested_Lateral_Deceleration: -0.125
  Requested_Vertical_Acceleration: -0.2
  Requested_Vertical_Deceleration: 0.2
  Landing_Approach_Height: 3
  Vertical_Landing_Speed_At_Ground: 0.1
  Q_Position: 1
  Q_Velocity: 1
  Q_Angular_Velocity: 1
  Q_Angles: 1
  Ctrl_R: 0.1
params:
  leg_length: 
    min: 20
    max: 300
    components: 
      - leg_1
      - leg_2
      - leg_3
      - leg_4
    parameter: Length
  arm_length:
    min: 400
    max: 800
    components: 
      - arm_1
      - arm_2
      - arm_3
      - arm_4
    parameter: Length
  cap_fuse_length:
    min: 400
    max: 800
    components: 
      - capsule_fuselage
    parameter: FUSE_CYL_LENGTH
  cap_fuse_height:
    min: 100
    max: 400
    components: 
      - capsule_fuselage
    parameter: VERT_DIAMETER
  cap_fuse_width:
    min: 100
    max: 400
    components: 
      - capsule_fuselage
    parameter: HORZ_DIAMETER