design_name: "TestQuad_Cargo"
description: "Test Study Parameters for direct2cad Run"
# The 'flight_paths' entry must be a list.  The 'analysis_type' is a
# single integer number.  All other FDM parameters can 
# be a single value or a list. If a list exists, it should be the same 
# size as the 'flight_path' list
num_samples: 100
fdm:
  Analysis_Type: 3
  Flight_Path: [1, 3, 4, 5]
  Requested_Lateral_Speed: [19, 21, 11, 10]
  Requested_Vertical_Speed: 1.1
  Q_Position: 1
  Q_Velocity: 1
  Q_Angular_Velocity: 1
  Q_Angles: 1
  Ctrl_R: 0.1
params:
  # for leg_1 - leg_4
  legs: 
    max_value: 300
    min_value: 20
    name: 
      - Leg
    parameter: Length
  # for arm_1 - arm 4
  arms:
    max_value: 800
    min_value: 75
    name: 
      - Arm
    parameter: Length
  cap_fuse_length:
    max_value: 500
    min_value: 10
    name: 
      - fuse
    parameter: length
  cap_fuse_height:
    max_value: 400
    min_value: 25
    name: 
      - fuse
    parameter: height
  cap_fuse_width:
    max_value: 400
    min_value: 25
    name: 
      - fuse
    parameter: width