design_name: MinimalUAV
description: Study Parameters for Minimal Platform direct2cad Run
corpus_type: UAV
num_samples: 1
fdm:
- Flight_Path: 9
- Requested_Lateral_Speed: 23
- Requested_Vertical_Speed: -5
- Requested_Vertical_Down_Speed: 5
- Requested_Lateral_Acceleration: 2
- Requested_Lateral_Deceleration: -3
- Requested_Vertical_Acceleration: -1
- Requested_Vertical_Deceleration: 1
- Q_Position: 1
- Q_Velocity: 0.5
- Q_Angular_Velocity: 1
- Q_Angles: 0.5
- Ctrl_R: 0.25
params:
- fuselage_floor_height:
  - max: 20
  - min: 20
- fuselage_width:
  - max: 190
  - min: 190
- fuselage_height:
  - max: 125
  - min: 125
- fuselage_cyl_length:
  - max: 270
  - min: 270
- bott_conn_rotation:
  - max: 45
  - min: 45
- hub_conn_hort_angle:
  - max: 90
  - min: 90
- z_angle:
  - max: 45
  - min: 45
cargo_mass:
- 0.001
