design_name: TailSitter3NarrowBody
description: Study Parameters for Tail Sitter Platform direct2cad Run
corpus_type: UAM
num_samples: 1
fdm:
- Analysis_Type: 3
- Flight_Path:
  - 1
  - 3
  - 4
  - 5
- Requested_Lateral_Speed:
  - 50
  - 32
  - 1
  - 46
- Requested_Vertical_Speed: 19
- Q_Position:
  - 1
  - 1
  - 1
  - 0.01
- Q_Velocity:
  - 1
  - 1
  - 1
  - 0.1
- Q_Angular_Velocity:
  - 1
  - 1
  - 1
  - 0.1
- Q_Angles: 1
- Ctrl_R: 0.1
params:
- fuse_length:
  - max: 2345
  - min: 2345
- fuse_diameter:
  - max: 1201
  - min: 1201
- fuse_mid_length:
  - max: 1517
  - min: 1517
- fuse_tail_diameter:
  - max: 107
  - min: 107
- fuse_floor_height:
  - max: 110
  - min: 110
- seat1_fb_pos:
  - max: 1523
  - min: 1523
- seat1_lr_pos:
  - max: 0
  - min: 0
- seat2_fb_pos:
  - max: 690
  - min: 690
- seat2_lr_pos:
  - max: 0
  - min: 0
- fuse_port_thickness:
  - max: 100
  - min: 100
- fuse_top_disp:
  - max: 0
  - min: 0
- fuse_bottom_disp:
  - max: 0
  - min: 0
- fuse_left_disp:
  - max: 0
  - min: 0
- fuse_right_disp:
  - max: 0
  - min: 0
- bar1_length:
  - max: 1000
  - min: 1000
- bar2_length:
  - max: 750
  - min: 750
- wing_chord:
  - max: 1400
  - min: 1400
- wing_span:
  - max: 8000
  - min: 8000
- wing_load:
  - max: 5000
  - min: 5000
- battery_voltage:
  - max: 840
  - min: 840
- battery_percent:
  - max: 100
  - min: 100
- cylinder_diameter:
  - max: 100
  - min: 100
- stear_wing_chord:
  - max: 500
  - min: 500
- stear_wing_span:
  - max: 3000
  - min: 3000
- stear_wing_load:
  - max: 1000
  - min: 1000
- stear_bar1_length:
  - max: 4000
  - min: 4000
