design_name: VUdoo
description: Study Parameters for Vudoo Platform direct2cad Run
corpus_type: UAM
num_samples: 1
fdm:
- Analysis_Type: 3
- Flight_Path:
  - 1
  - 3
  - 4
  - 5
- Requested_Lateral_Speed_1: 48
- Requested_Lateral_Speed_5: 31
- Q_Position_5: 0.01
- Q_Velocity_5: 0.01
- Q_Angular_Velocity_5: 0.1
- Q_Angles_5: 0.01
- R_5: 0.1
params:
- fuse_length:
  - max: 2000
  - min: 2000
- fuse_sphere_diameter:
  - max: 1520
  - min: 1520
- fuse_middle_length:
  - max: 750
  - min: 750
- fuse_tail_diameter:
  - max: 200
  - min: 200
- fuse_floor_height:
  - max: 150
  - min: 150
- seat1_fb_pos:
  - max: 1000
  - min: 1000
- seat1_lr_pos:
  - max: -210
  - min: -210
- seat2_fb_pos:
  - max: 1000
  - min: 1000
- seat2_lr_pos:
  - max: 210
  - min: 210
- fuse_top_disp:
  - max: 300
  - min: 300
- fuse_bottom_disp:
  - max: 300
  - min: 300
- fuse_left_disp:
  - max: 0
  - min: 0
- fuse_right_disp:
  - max: 0
  - min: 0
- wing_chord:
  - max: 1200
  - min: 1200
- wing_span:
  - max: 10000
  - min: 10000
- wing_load:
  - max: 15000
  - min: 15000
- battery_voltage:
  - max: 569
  - min: 569
- battery_percent:
  - max: 61.6
  - min: 61.6
- cylinder_diameter:
  - max: 100
  - min: 100
- spacer1_length:
  - max: 500
  - min: 500
- spacer2_length:
  - max: 1300
  - min: 1300
- stear_wing_chord:
  - max: 500
  - min: 500
- stear_wing_span:
  - max: 2000
  - min: 2000
- stear_wing_load:
  - max: 1000
  - min: 1000
- stear_bar1_length:
  - max: 4000
  - min: 4000
